# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/kitakami-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter ivy karin karin_windy satsuki sumire suzuran,$(TARGET_DEVICE)),)

ifeq ($(strip $(BOARD_NFC_CHIPSET)),pn547)
endif
endif
