# Copyright (C) 2026 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Hand-assembled, not generated by setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter ivy karin karin_windy satsuki sumire suzuran,$(TARGET_DEVICE)),)

include $(CLEAR_VARS)
LOCAL_MODULE := ArtFilterCamera-xxhdpi-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := priv-app/ArtFilterCamera-xxhdpi-release/ArtFilterCamera-xxhdpi-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/priv-app/ArtFilterCamera-xxhdpi-release/ArtFilterCamera-xxhdpi-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_PREBUILT_JNI_LIBS := \
    priv-app/ArtFilterCamera-xxhdpi-release/lib/arm/libnativeeffectengine.so \
    priv-app/ArtFilterCamera-xxhdpi-release/lib/arm/libyuvframe.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := CameraCommon
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := priv-app/CameraCommon/CameraCommon.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/priv-app/CameraCommon/CameraCommon.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := DualCamera-xxhdpi-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := priv-app/DualCamera-xxhdpi-release/DualCamera-xxhdpi-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/priv-app/DualCamera-xxhdpi-release/DualCamera-xxhdpi-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_PREBUILT_JNI_LIBS := \
    priv-app/DualCamera-xxhdpi-release/lib/arm/libyuvframe.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FaceFusionCamera-xxhdpi-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := priv-app/FaceFusionCamera-xxhdpi-release/FaceFusionCamera-xxhdpi-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/priv-app/FaceFusionCamera-xxhdpi-release/FaceFusionCamera-xxhdpi-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_PREBUILT_JNI_LIBS := \
    priv-app/FaceFusionCamera-xxhdpi-release/lib/arm/libcameracommonimageconvertor.so \
    priv-app/FaceFusionCamera-xxhdpi-release/lib/arm/libfacefusioncameranative.so \
    priv-app/FaceFusionCamera-xxhdpi-release/lib/arm/libyuvframe.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := OnlineRemoteCamera-xxhdpi-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := priv-app/OnlineRemoteCamera-xxhdpi-release/OnlineRemoteCamera-xxhdpi-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/priv-app/OnlineRemoteCamera-xxhdpi-release/OnlineRemoteCamera-xxhdpi-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_PREBUILT_JNI_LIBS := \
    priv-app/OnlineRemoteCamera-xxhdpi-release/lib/arm/libcameracommonimageconvertor.so \
    priv-app/OnlineRemoteCamera-xxhdpi-release/lib/arm/libyuvframe.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := SemcCamera3D-xxhdpi-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := priv-app/SemcCamera3D-xxhdpi-release/SemcCamera3D-xxhdpi-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/priv-app/SemcCamera3D-xxhdpi-release/SemcCamera3D-xxhdpi-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_PREBUILT_JNI_LIBS := \
    priv-app/SemcCamera3D-xxhdpi-release/lib/arm/libimagebank.so \
    priv-app/SemcCamera3D-xxhdpi-release/lib/arm/libnativebytearray.so \
    priv-app/SemcCamera3D-xxhdpi-release/lib/arm/libstitchengine.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := SemcCameraUI-noGesture-xxhdpi-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := priv-app/SemcCameraUI-noGesture-xxhdpi-release/SemcCameraUI-noGesture-xxhdpi-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/priv-app/SemcCameraUI-noGesture-xxhdpi-release/SemcCameraUI-noGesture-xxhdpi-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := StylePortrait
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := priv-app/StylePortrait/StylePortrait.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/priv-app/StylePortrait/StylePortrait.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_PREBUILT_JNI_LIBS := \
    priv-app/StylePortrait/lib/arm/libarcsoft_beauty_shot.so \
    priv-app/StylePortrait/lib/arm/libDefocus.so \
    priv-app/StylePortrait/lib/arm/libjni_filters.so \
    priv-app/StylePortrait/lib/arm/liboptimizerotate.so \
    priv-app/StylePortrait/lib/arm/liboptimize.so \
    priv-app/StylePortrait/lib/arm/libsomccpuaffinity.so \
    priv-app/StylePortrait/lib/arm/libsomcfacebeauty.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := SuperVideoCamera-xxhdpi-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := priv-app/SuperVideoCamera-xxhdpi-release/SuperVideoCamera-xxhdpi-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/priv-app/SuperVideoCamera-xxhdpi-release/SuperVideoCamera-xxhdpi-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := TimeShiftCamera-xxhdpi-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := priv-app/TimeShiftCamera-xxhdpi-release/TimeShiftCamera-xxhdpi-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/priv-app/TimeShiftCamera-xxhdpi-release/TimeShiftCamera-xxhdpi-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_PREBUILT_JNI_LIBS := \
    priv-app/TimeShiftCamera-xxhdpi-release/lib/arm/libcameracommonimageconvertor.so \
    priv-app/TimeShiftCamera-xxhdpi-release/lib/arm/libTimeShiftNative.so \
    priv-app/TimeShiftCamera-xxhdpi-release/lib/arm/libyuvframe.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ar-effect
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := app/ar-effect/ar-effect.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/app/ar-effect/ar-effect.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
LOCAL_MULTILIB := 32
LOCAL_PREBUILT_JNI_LIBS := \
    app/ar-effect/lib/arm/libArEffectFw.so \
    app/ar-effect/lib/arm/libHandAreaDetectA.so \
    app/ar-effect/lib/arm/libhandareadetect_effector.so \
    app/ar-effect/lib/arm/libHandAreaDetectG.so \
    app/ar-effect/lib/arm/libHandAreaDetectM.so \
    app/ar-effect/lib/arm/libHandAreaDetectP.so \
    app/ar-effect/lib/arm/libimageconvertor.so \
    app/ar-effect/lib/arm/libJPGLoader.so \
    app/ar-effect/lib/arm/libKmyCore.so \
    app/ar-effect/lib/arm/libKmyGame.so \
    app/ar-effect/lib/arm/libKmyPlayer.so \
    app/ar-effect/lib/arm/libsampleJni.so \
    app/ar-effect/lib/arm/libsmartar.so \
    app/ar-effect/lib/arm/libstlport_shared.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := CameraAddonPermission-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := app/CameraAddonPermission-release/CameraAddonPermission-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/app/CameraAddonPermission-release/CameraAddonPermission-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := CameraCommonPermission-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := app/CameraCommonPermission-release/CameraCommonPermission-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/app/CameraCommonPermission-release/CameraCommonPermission-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := CameraExtensionPermission-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := app/CameraExtensionPermission-release/CameraExtensionPermission-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/app/CameraExtensionPermission-release/CameraExtensionPermission-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ImageProcessorPermission-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := app/ImageProcessorPermission-release/ImageProcessorPermission-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/app/ImageProcessorPermission-release/ImageProcessorPermission-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := StickerCreator
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := app/StickerCreator/StickerCreator.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/app/StickerCreator/StickerCreator.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
LOCAL_MULTILIB := 32
LOCAL_PREBUILT_JNI_LIBS := \
    app/StickerCreator/lib/arm/libCutoutNative.so \
    app/StickerCreator/lib/arm/libgif.so \
    app/StickerCreator/lib/arm/libopencv_java3.so \
    app/StickerCreator/lib/arm/libstlport_shared.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := StyleBlue-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := app/StyleBlue-release/StyleBlue-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/app/StyleBlue-release/StyleBlue-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := StyleBubble-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := app/StyleBubble-release/StyleBubble-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/app/StyleBubble-release/StyleBubble-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := StyleDaily-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := app/StyleDaily-release/StyleDaily-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/app/StyleDaily-release/StyleDaily-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := StylePaint-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := app/StylePaint-release/StylePaint-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/app/StylePaint-release/StylePaint-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := StyleRed-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := app/StyleRed-release/StyleRed-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/app/StyleRed-release/StyleRed-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := StyleStar-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := app/StyleStar-release/StyleStar-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/app/StyleStar-release/StyleStar-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := StyleSunshine-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := app/StyleSunshine-release/StyleSunshine-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/app/StyleSunshine-release/StyleSunshine-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := StyleSuntan-release
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := app/StyleSuntan-release/StyleSuntan-release.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/app/StyleSuntan-release/StyleSuntan-release.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := SystemUiVisibilityPermission
LOCAL_MODULE_OWNER := sony
LOCAL_SRC_FILES := app/SystemUiVisibilityPermission/SystemUiVisibilityPermission.apk
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/app/SystemUiVisibilityPermission/SystemUiVisibilityPermission.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

endif
