# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2017-2026 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_COPY_FILES += \
    vendor/sony/suzuran/proprietary/bin/qseecomd:$(TARGET_COPY_OUT_SYSTEM)/bin/qseecomd \
    vendor/sony/suzuran/proprietary/bin/sensors.qcom:$(TARGET_COPY_OUT_SYSTEM)/bin/sensors.qcom \
    vendor/sony/suzuran/proprietary/etc/acdbdata/Sony/Sony_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Sony/Sony_Bluetooth_cal.acdb \
    vendor/sony/suzuran/proprietary/etc/acdbdata/Sony/Sony_General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Sony/Sony_General_cal.acdb \
    vendor/sony/suzuran/proprietary/etc/acdbdata/Sony/Sony_Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Sony/Sony_Global_cal.acdb \
    vendor/sony/suzuran/proprietary/etc/acdbdata/Sony/Sony_Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Sony/Sony_Handset_cal.acdb \
    vendor/sony/suzuran/proprietary/etc/acdbdata/Sony/Sony_Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Sony/Sony_Hdmi_cal.acdb \
    vendor/sony/suzuran/proprietary/etc/acdbdata/Sony/Sony_Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Sony/Sony_Headset_cal.acdb \
    vendor/sony/suzuran/proprietary/etc/acdbdata/Sony/Sony_Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Sony/Sony_Speaker_cal.acdb \
    vendor/sony/suzuran/proprietary/etc/firmware/BCM43xx.hcd:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/BCM43xx.hcd \
    vendor/sony/suzuran/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/sony/suzuran/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/sony/suzuran/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/sony/suzuran/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_4_0.fw \
    vendor/sony/suzuran/proprietary/etc/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_6_0.fw \
    vendor/sony/suzuran/proprietary/etc/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_8_0.fw \
    vendor/sony/suzuran/proprietary/etc/firmware/touch_module_id_0x30.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_module_id_0x30.img \
    vendor/sony/suzuran/proprietary/etc/firmware/touch_module_id_0x31.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_module_id_0x31.img \
    vendor/sony/suzuran/proprietary/etc/firmware/touch_module_id_0x32.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_module_id_0x32.img \
    vendor/sony/suzuran/proprietary/etc/firmware/touch_module_id_0x33.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_module_id_0x33.img \
    vendor/sony/suzuran/proprietary/etc/firmware/touch_module_id_0x40.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_module_id_0x40.img \
    vendor/sony/suzuran/proprietary/etc/firmware/touch_module_id_0x41.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_module_id_0x41.img \
    vendor/sony/suzuran/proprietary/etc/firmware/touch_module_id_0x42.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_module_id_0x42.img \
    vendor/sony/suzuran/proprietary/etc/firmware/touch_module_id_0x43.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_module_id_0x43.img \
    vendor/sony/suzuran/proprietary/etc/firmware/touch_module_id_0x44.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_module_id_0x44.img \
    vendor/sony/suzuran/proprietary/etc/firmware/touch_module_id_0x45.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_module_id_0x45.img \
    vendor/sony/suzuran/proprietary/etc/firmware/wlan/bcmdhd/fw_bcmdhd_apsta.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/wlan/bcmdhd/fw_bcmdhd_apsta.bin \
    vendor/sony/suzuran/proprietary/etc/firmware/wlan/bcmdhd/fw_bcmdhd.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/wlan/bcmdhd/fw_bcmdhd.bin \
    vendor/sony/suzuran/proprietary/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/sony/suzuran/proprietary/etc/touch_fw_update.sh:$(TARGET_COPY_OUT_SYSTEM)/etc/touch_fw_update.sh \
    vendor/sony/suzuran/proprietary/lib64/hw/libpn547_fw.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/libpn547_fw.so \
    vendor/sony/suzuran/proprietary/lib64/libcamera_clientsemc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libcamera_clientsemc.so \
    vendor/sony/suzuran/proprietary/lib64/libcameralight.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libcameralight.so \
    vendor/sony/suzuran/proprietary/lib64/libcom_fingerprints_service.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libcom_fingerprints_service.so \
    vendor/sony/suzuran/proprietary/lib64/libdataitems.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libdataitems.so \
    vendor/sony/suzuran/proprietary/lib64/libdrmfs.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libdrmfs.so \
    vendor/sony/suzuran/proprietary/lib64/libidd.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libidd.so \
    vendor/sony/suzuran/proprietary/lib64/libQSEEComAPI.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libQSEEComAPI.so \
    vendor/sony/suzuran/proprietary/lib64/librpmb.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/librpmb.so \
    vendor/sony/suzuran/proprietary/lib64/libssd.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libssd.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_color_ctrl_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_color_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_debug_display_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_debug_display_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_exposure_ctrl_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_exposure_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_face_detector_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_face_detector_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_flicker_detector_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_flicker_detector_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_focus_stats_conv_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_focus_stats_conv_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_food_comp_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_food_comp_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_food_detector_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_food_detector_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_hal_ctrl_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_hal_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_hdr_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_hdr_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_idt_ctrl_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_idt_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_image_conv_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_image_conv_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_iq_ctrl_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_iq_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_jpeg_enc_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_jpeg_enc_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_lens_ctrl_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_lens_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_motion_estimation_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_motion_estimation_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_multiframe_nr_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_multiframe_nr_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_object_tracker_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_object_tracker_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_req_ctrl_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_req_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_scene_detector_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_scene_detector_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_snapshot_ctrl_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_snapshot_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_splitter_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_splitter_plugin.so \
    vendor/sony/suzuran/proprietary/lib/camera/libexcal_stream_ctrl_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/camera/libexcal_stream_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/lib/libcacao_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcacao_client.so \
    vendor/sony/suzuran/proprietary/lib/libcacao_common.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcacao_common.so \
    vendor/sony/suzuran/proprietary/lib/libcacao_imgproc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcacao_imgproc.so \
    vendor/sony/suzuran/proprietary/lib/libcacao_jpeg.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcacao_jpeg.so \
    vendor/sony/suzuran/proprietary/lib/libcacao_service.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcacao_service.so \
    vendor/sony/suzuran/proprietary/lib/libcacao_system.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcacao_system.so \
    vendor/sony/suzuran/proprietary/lib/libcamera_clientsemc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcamera_clientsemc.so \
    vendor/sony/suzuran/proprietary/lib/libcameralight.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcameralight.so \
    vendor/sony/suzuran/proprietary/lib/libcammw.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcammw.so \
    vendor/sony/suzuran/proprietary/lib/libcom_fingerprints_service.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcom_fingerprints_service.so \
    vendor/sony/suzuran/proprietary/lib/libdrmfs.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdrmfs.so \
    vendor/sony/suzuran/proprietary/lib/libexcal_core.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libexcal_core.so \
    vendor/sony/suzuran/proprietary/lib/libexcal_legacy.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libexcal_legacy.so \
    vendor/sony/suzuran/proprietary/lib/libexcal_pal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libexcal_pal.so \
    vendor/sony/suzuran/proprietary/lib/libexcal_system.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libexcal_system.so \
    vendor/sony/suzuran/proprietary/lib/libidd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libidd.so \
    vendor/sony/suzuran/proprietary/lib/libmm-qcamera.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmm-qcamera.so \
    vendor/sony/suzuran/proprietary/lib/liboemcamera.so:$(TARGET_COPY_OUT_SYSTEM)/lib/liboemcamera.so \
    vendor/sony/suzuran/proprietary/lib/libQSEEComAPI.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libQSEEComAPI.so \
    vendor/sony/suzuran/proprietary/lib/librpmb.so:$(TARGET_COPY_OUT_SYSTEM)/lib/librpmb.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_alfortrsc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_alfortrsc.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_alfort.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_alfort.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_bordeauxrsc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_bordeauxrsc.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_bordeaux.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_bordeaux.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_canelersc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_canelersc.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_canele.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_canele.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_chokoballcmn.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_chokoballcmn.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_chokoballpal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_chokoballpal.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_marblersc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_marblersc.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_marble.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_marble.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_melonpanrsc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_melonpanrsc.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_melonpan.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_melonpan.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_mugichocorsc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_mugichocorsc.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_mugichoco.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_mugichoco.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_raisinrsc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_raisinrsc.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_raisin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_raisin.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_spicarsc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_spicarsc.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_spica.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_spica.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_thermal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_thermal.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_topporsc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_topporsc.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_toppo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_toppo.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_yummyrsc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_yummyrsc.so \
    vendor/sony/suzuran/proprietary/lib/libsomc_yummy.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsomc_yummy.so \
    vendor/sony/suzuran/proprietary/lib/libsony_fooddetect.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsony_fooddetect.so \
    vendor/sony/suzuran/proprietary/lib/libsony_naruto.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsony_naruto.so \
    vendor/sony/suzuran/proprietary/lib/libssd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libssd.so \
    vendor/sony/suzuran/proprietary/vendor/camera/default.dat:$(TARGET_COPY_OUT_VENDOR)/camera/default.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/flash.dat:$(TARGET_COPY_OUT_VENDOR)/camera/flash.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/color_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/dataflow.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/debug_mgr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/debug_mgr.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/exposure_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/exposure_ctrl_diagram.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/exposure_ctrl_gamma.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/exposure_ctrl_gamma.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/face_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/flicker_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/focus_stats_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/focus_stats_conv.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/food_comp_yummy.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/food_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/food_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/hal_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/hal_ctrl_platform_abf.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/hal_ctrl_platform_abf.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/hal_ctrl_platform_asf_lin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/hal_ctrl_platform_asf_lin.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/hal_ctrl_platform_asf_stp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/hal_ctrl_platform_asf_stp.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/hal_ctrl_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/hal_ctrl_platform.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/hal_ctrl_platform_gic.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/hal_ctrl_platform_gic.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/hdr_comp.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/idt_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/image_conv_canele.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/image_conv_canele.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/image_conv.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/image_conv_marble.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/image_conv_raisin.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/image_conv_spica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/image_conv_spica.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0_IMX241.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0_IMX241.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/jpeg_enc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/jpeg_enc.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/lens_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/motion_estimation.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/multiframe_nr.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/multiframe_nr_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/multiframe_nr_melonpan.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/multiframe_nr_mugichoco.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/multiframe_nr_mugichoco.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/multiframe_nr_toppo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/multiframe_nr_toppo.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/object_tracker.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/scene_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/LGI05BN0/snapshot_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI05BN0/snapshot_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/color_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/dataflow.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/debug_mgr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/debug_mgr.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/exposure_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/exposure_ctrl_diagram.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/exposure_ctrl_gamma.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/exposure_ctrl_gamma.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/face_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/flicker_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/focus_stats_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/focus_stats_conv.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/food_comp_yummy.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/food_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/food_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/hal_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/hal_ctrl_platform_abf.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/hal_ctrl_platform_abf.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/hal_ctrl_platform_asf_lin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/hal_ctrl_platform_asf_lin.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/hal_ctrl_platform_asf_stp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/hal_ctrl_platform_asf_stp.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/hal_ctrl_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/hal_ctrl_platform.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/hal_ctrl_platform_gic.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/hal_ctrl_platform_gic.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/hdr_comp.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/idt_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/image_conv_canele.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/image_conv_canele.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/image_conv.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/image_conv_marble.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/image_conv_raisin.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/image_conv_spica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/image_conv_spica.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0_IMX241.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0_IMX241.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/jpeg_enc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/jpeg_enc.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/lens_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/motion_estimation.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/multiframe_nr.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/multiframe_nr_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/multiframe_nr_melonpan.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/multiframe_nr_mugichoco.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/multiframe_nr_mugichoco.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/multiframe_nr_toppo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/multiframe_nr_toppo.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/object_tracker.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/scene_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SEM05BN0/snapshot_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM05BN0/snapshot_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/snapshot.dat:$(TARGET_COPY_OUT_VENDOR)/camera/snapshot.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0_BU64747GWZ.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0_BU64747GWZ.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0_BU64747GWZ_XCF.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0_BU64747GWZ_XCF.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0_BU64747GWZ_XFW.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0_BU64747GWZ_XFW.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/color_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/dataflow.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/debug_mgr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/debug_mgr.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/exposure_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/exposure_ctrl_diagram.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/exposure_ctrl_gamma.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/exposure_ctrl_gamma.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/face_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/flicker_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/focus_stats_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/focus_stats_conv.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/food_comp_yummy.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/food_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/food_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/hal_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/hal_ctrl_platform_abf.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/hal_ctrl_platform_abf.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/hal_ctrl_platform_asf_lin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/hal_ctrl_platform_asf_lin.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/hal_ctrl_platform_asf_stp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/hal_ctrl_platform_asf_stp.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/hal_ctrl_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/hal_ctrl_platform.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/hal_ctrl_platform_gic.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/hal_ctrl_platform_gic.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/hdr_comp.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/idt_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/image_conv_canele.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/image_conv_canele.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/image_conv.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/image_conv_marble.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/image_conv_raisin.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/image_conv_spica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/image_conv_spica.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0_IMX300.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0_IMX300.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/jpeg_enc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/jpeg_enc.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/lens_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/motion_estimation.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/multiframe_nr.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/multiframe_nr_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/multiframe_nr_melonpan.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/multiframe_nr_mugichoco.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/multiframe_nr_mugichoco.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/multiframe_nr_toppo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/multiframe_nr_toppo.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/object_tracker.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/scene_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS0/snapshot_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS0/snapshot_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1_BU64747GWZ.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1_BU64747GWZ.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1_BU64747GWZ_XCF.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1_BU64747GWZ_XCF.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1_BU64747GWZ_XFW.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1_BU64747GWZ_XFW.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/color_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/dataflow.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/debug_mgr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/debug_mgr.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/exposure_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/exposure_ctrl_diagram.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/exposure_ctrl_gamma.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/exposure_ctrl_gamma.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/face_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/flicker_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/focus_stats_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/focus_stats_conv.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/food_comp_yummy.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/food_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/food_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/hal_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/hal_ctrl_platform_abf.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/hal_ctrl_platform_abf.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/hal_ctrl_platform_asf_lin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/hal_ctrl_platform_asf_lin.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/hal_ctrl_platform_asf_stp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/hal_ctrl_platform_asf_stp.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/hal_ctrl_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/hal_ctrl_platform.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/hal_ctrl_platform_gic.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/hal_ctrl_platform_gic.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/hdr_comp.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/idt_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/image_conv_canele.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/image_conv_canele.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/image_conv.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/image_conv_marble.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/image_conv_raisin.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/image_conv_spica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/image_conv_spica.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1_IMX300.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1_IMX300.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/jpeg_enc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/jpeg_enc.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/lens_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/motion_estimation.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/multiframe_nr.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/multiframe_nr_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/multiframe_nr_melonpan.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/multiframe_nr_mugichoco.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/multiframe_nr_mugichoco.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/multiframe_nr_toppo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/multiframe_nr_toppo.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/object_tracker.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/scene_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS1/snapshot_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS1/snapshot_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2_BU64747GWZ.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2_BU64747GWZ.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2_BU64747GWZ_XCF.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2_BU64747GWZ_XCF.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2_BU64747GWZ_XFW.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2_BU64747GWZ_XFW.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/color_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/dataflow.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/debug_mgr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/debug_mgr.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/exposure_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/exposure_ctrl_diagram.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/exposure_ctrl_gamma.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/exposure_ctrl_gamma.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/face_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/flicker_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/focus_stats_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/focus_stats_conv.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/food_comp_yummy.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/food_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/food_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/hal_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/hal_ctrl_platform_abf.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/hal_ctrl_platform_abf.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/hal_ctrl_platform_asf_lin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/hal_ctrl_platform_asf_lin.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/hal_ctrl_platform_asf_stp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/hal_ctrl_platform_asf_stp.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/hal_ctrl_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/hal_ctrl_platform.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/hal_ctrl_platform_gic.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/hal_ctrl_platform_gic.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/hdr_comp.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/idt_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/image_conv_canele.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/image_conv_canele.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/image_conv.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/image_conv_marble.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/image_conv_raisin.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/image_conv_spica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/image_conv_spica.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2_IMX300.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2_IMX300.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/jpeg_enc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/jpeg_enc.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/lens_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/motion_estimation.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/multiframe_nr.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/multiframe_nr_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/multiframe_nr_melonpan.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/multiframe_nr_mugichoco.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/multiframe_nr_mugichoco.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/multiframe_nr_toppo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/multiframe_nr_toppo.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/object_tracker.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/scene_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS2/snapshot_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS2/snapshot_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3_BU64747GWZ.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3_BU64747GWZ.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3_BU64747GWZ_XCF.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3_BU64747GWZ_XCF.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3_BU64747GWZ_XFW.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3_BU64747GWZ_XFW.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/color_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/dataflow.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/debug_mgr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/debug_mgr.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/exposure_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/exposure_ctrl_diagram.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/exposure_ctrl_gamma.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/exposure_ctrl_gamma.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/face_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/flicker_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/focus_stats_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/focus_stats_conv.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/food_comp_yummy.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/food_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/food_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/hal_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/hal_ctrl_platform_abf.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/hal_ctrl_platform_abf.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/hal_ctrl_platform_asf_lin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/hal_ctrl_platform_asf_lin.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/hal_ctrl_platform_asf_stp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/hal_ctrl_platform_asf_stp.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/hal_ctrl_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/hal_ctrl_platform.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/hal_ctrl_platform_gic.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/hal_ctrl_platform_gic.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/hdr_comp.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/idt_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/image_conv_canele.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/image_conv_canele.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/image_conv.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/image_conv_marble.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/image_conv_raisin.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/image_conv_spica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/image_conv_spica.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3_IMX300.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3_IMX300.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/jpeg_enc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/jpeg_enc.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/lens_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/motion_estimation.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/multiframe_nr.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/multiframe_nr_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/multiframe_nr_melonpan.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/multiframe_nr_mugichoco.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/multiframe_nr_mugichoco.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/multiframe_nr_toppo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/multiframe_nr_toppo.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/object_tracker.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/scene_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS3/snapshot_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS3/snapshot_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4_BU64747GWZ.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4_BU64747GWZ.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4_BU64747GWZ_XCF.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4_BU64747GWZ_XCF.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4_BU64747GWZ_XFW.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4_BU64747GWZ_XFW.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/color_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/dataflow.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/debug_mgr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/debug_mgr.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/exposure_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/exposure_ctrl_diagram.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/exposure_ctrl_gamma.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/exposure_ctrl_gamma.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/face_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/flicker_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/focus_stats_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/focus_stats_conv.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/food_comp_yummy.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/food_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/food_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/hal_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/hal_ctrl_platform_abf.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/hal_ctrl_platform_abf.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/hal_ctrl_platform_asf_lin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/hal_ctrl_platform_asf_lin.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/hal_ctrl_platform_asf_stp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/hal_ctrl_platform_asf_stp.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/hal_ctrl_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/hal_ctrl_platform.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/hal_ctrl_platform_gic.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/hal_ctrl_platform_gic.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/hdr_comp.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/idt_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/image_conv_canele.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/image_conv_canele.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/image_conv.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/image_conv_marble.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/image_conv_raisin.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/image_conv_spica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/image_conv_spica.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4_IMX300.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4_IMX300.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/jpeg_enc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/jpeg_enc.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/lens_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/motion_estimation.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/multiframe_nr.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/multiframe_nr_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/multiframe_nr_melonpan.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/multiframe_nr_mugichoco.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/multiframe_nr_mugichoco.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/multiframe_nr_toppo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/multiframe_nr_toppo.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/object_tracker.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/scene_detector.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/SOI25BS4/snapshot_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI25BS4/snapshot_ctrl.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/streaming.dat:$(TARGET_COPY_OUT_VENDOR)/camera/streaming.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/supported.dat:$(TARGET_COPY_OUT_VENDOR)/camera/supported.dat \
    vendor/sony/suzuran/proprietary/vendor/camera/version.dat:$(TARGET_COPY_OUT_VENDOR)/camera/version.dat \
    vendor/sony/suzuran/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/sony/suzuran/proprietary/vendor/firmware/tzfingerprint.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.b00 \
    vendor/sony/suzuran/proprietary/vendor/firmware/tzfingerprint.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.b01 \
    vendor/sony/suzuran/proprietary/vendor/firmware/tzfingerprint.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.b02 \
    vendor/sony/suzuran/proprietary/vendor/firmware/tzfingerprint.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.b03 \
    vendor/sony/suzuran/proprietary/vendor/firmware/tzfingerprint.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.mdt \
    vendor/sony/suzuran/proprietary/vendor/lib64/hw/fingerprint.msm8994.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fingerprint.msm8994.so \
    vendor/sony/suzuran/proprietary/vendor/lib64/libdataitems.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdataitems.so \
    vendor/sony/suzuran/proprietary/vendor/lib64/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmfs.so \
    vendor/sony/suzuran/proprietary/vendor/lib64/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmtime.so \
    vendor/sony/suzuran/proprietary/vendor/lib64/lib_fpc_tac_shared.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib_fpc_tac_shared.so \
    vendor/sony/suzuran/proprietary/vendor/lib64/libidd.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libidd.so \
    vendor/sony/suzuran/proprietary/vendor/lib64/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libQSEEComAPI.so \
    vendor/sony/suzuran/proprietary/vendor/lib64/librpmb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librpmb.so \
    vendor/sony/suzuran/proprietary/vendor/lib64/lib-sec-disp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-sec-disp.so \
    vendor/sony/suzuran/proprietary/vendor/lib64/libsecureui.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsecureui.so \
    vendor/sony/suzuran/proprietary/vendor/lib64/libsecureui_svcsock.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsecureui_svcsock.so \
    vendor/sony/suzuran/proprietary/vendor/lib64/libsensor1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsensor1.so \
    vendor/sony/suzuran/proprietary/vendor/lib64/libsensor_reg.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsensor_reg.so \
    vendor/sony/suzuran/proprietary/vendor/lib64/libssd.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libssd.so \
    vendor/sony/suzuran/proprietary/vendor/lib64/libStDrvInt.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libStDrvInt.so \
    vendor/sony/suzuran/proprietary/vendor/lib64/sensors.ssc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/sensors.ssc.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_color_ctrl_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_color_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_debug_display_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_debug_display_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_exposure_ctrl_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_exposure_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_face_detector_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_face_detector_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_flicker_detector_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_flicker_detector_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_focus_stats_conv_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_focus_stats_conv_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_food_comp_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_food_comp_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_food_detector_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_food_detector_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_hal_ctrl_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_hal_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_hdr_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_hdr_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_idt_ctrl_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_idt_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_image_conv_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_image_conv_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_iq_ctrl_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_iq_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_jpeg_enc_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_jpeg_enc_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_lens_ctrl_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_lens_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_motion_estimation_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_motion_estimation_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_multiframe_nr_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_multiframe_nr_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_object_tracker_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_object_tracker_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_req_ctrl_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_req_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_scene_detector_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_scene_detector_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_snapshot_ctrl_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_snapshot_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_splitter_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_splitter_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/camera/libexcal_stream_ctrl_plugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/libexcal_stream_ctrl_plugin.so \
    vendor/sony/suzuran/proprietary/vendor/lib/hw/fingerprint.msm8994.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/fingerprint.msm8994.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libdataitems.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdataitems.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmfs.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmtime.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libfastcvadsp_stub.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfastcvadsp_stub.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libflash_pmic.so:$(TARGET_COPY_OUT_VENDOR)/lib/libflash_pmic.so \
    vendor/sony/suzuran/proprietary/vendor/lib/lib_fpc_tac_shared.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_fpc_tac_shared.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libidd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libidd.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libjpegdhw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdhw.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libjpegdmahw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdmahw.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libjpegehw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegehw.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libmmipl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmipl.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libQSEEComAPI.so \
    vendor/sony/suzuran/proprietary/vendor/lib/librpmb.so:$(TARGET_COPY_OUT_VENDOR)/lib/librpmb.so \
    vendor/sony/suzuran/proprietary/vendor/lib/lib-sec-disp.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-sec-disp.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libsecureui.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsecureui.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libsecureui_svcsock.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsecureui_svcsock.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libsensor1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensor1.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libsensor_reg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensor_reg.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libsony_fooddetect.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsony_fooddetect.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libsony_naruto.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsony_naruto.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libssd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libssd.so \
    vendor/sony/suzuran/proprietary/vendor/lib/libStDrvInt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libStDrvInt.so \
    vendor/sony/suzuran/proprietary/vendor/lib/sensors.ssc.so:$(TARGET_COPY_OUT_VENDOR)/lib/sensors.ssc.so
